### ISSUE TITLE
Conflicting arguments are only discovered at runtime

### ISSUE THREAD

**Issue by clintval** [fulcrumgenomics/sopt#21]
In a large project with many CLI arguments and tools its common to accidentally add a duplicate argument such as the following:

```scala
/** An example command. */
@clp(description=
    """
     |An example program that greets people. The `greeting` argument is optional
     |since it has a default.
    """)
class Greet(
  @arg(flag='g', doc="The greeting.")                       val greeting: String = "Hello",
  @arg(flag='n', doc="Someone's name.")                     val name: String,
  @arg(flag='g', doc="Another argument starting with G.")   val default: String = "Default",
) extends Tool {
  override def execute(): Unit = System.out.println(s"$greeting $name!")
}
```

No exceptions are raised on compilation so this bug can only be discovered at run-time:

```
Exception in thread "main" com.fulcrumgenomics.sopt.cmdline.CommandLineException: g has already been used.  Conflicting arguments are: 'greeting' and 'default'
```

Is it possible for `sopt` to prevent successful compilation if duplicate arguments are used?

**Comment by nh13** [comment]
While it may be possible to use java annotation processors or some similar library that extends them, it may be better to add a unit test that tests each CLP generates it's command line successfully:

```scala
ParsingUtil.findClpClasses[SomeClass](packageList).foreach { case (clazz, _) =>
  new CommandLineProgramParser(clp)
}
```
where `packageList` is the list of packages that contain your CLPs.
