### ISSUE TITLE
Non-printing characters are not fancifully displayed on the CLI

### ISSUE THREAD

**Issue by clintval** [fulcrumgenomics/sopt#27]
If you have an argument like:

```scala
@arg(flag = 'd', doc = "The input file data delimiter.") val delimiter: Char = '\t'
```

Then `sopt` will render this on the CLI:

```
-d Char, --delimiter=Char     The input file data delimiter. [Default: ]. 
```

I would have expected non-printing characters to be displayed fancifully for human reading:

```
-d Char, --delimiter=Char     The input file data delimiter. [Default: \t]. 
```

**Comment by nh13** [comment]
I think the offending code is here:
https://github.com/fulcrumgenomics/sopt/blob/6330673af6ae60cd8c420af62ec3d88fd5318a3b/src/main/scala/com/fulcrumgenomics/sopt/cmdline/ClpArgumentDefinitionPrinting.scala#L108-L116

And we probably need something like:
https://github.com/fulcrumgenomics/dagr/blob/ec4a86b1403308ca397b6473d52deffc575c2b4d/core/src/main/scala/dagr/core/tasksystem/ProcessTask.scala#L36-L47

Care to make a PR?

**Comment by clintval** [comment]
Sure! I'll give it a shot.
